### ISSUE TITLE
Instant respawn

### ISSUE THREAD

**Issue by jjenki11** [rtcw-nihi/ospx#119]
On adlernest_b5, axis spawned instantly after being gibbed or tapping out, regardless of the respawn timer.

**Comment by krazykaze81** [comment]
https://streamable.com/mw9qxr

**Comment by krazykaze81** [comment]
We confirmed this issue trying to find solution

**Comment by rtcw-nihi** [comment]
https://github.com/rtcw-nihi/ospx/commit/42bd90484a6c98912aef50f19ef64a00f450bcc5
