### ISSUE TITLE
Stats vs /statsall inconsistencies

### ISSUE THREAD

**Issue by donkz** [rtcw-nihi/ospx#151]
There are differences in how stats are printed out to client log

end game result looks like this

^7Overall stats for: ^zdonka ^7(^21^7 Round)

Weapon     Acrcy Hits/Atts Kills Deaths Headshots
-------------------------------------------------
^zKnife    : ^7  0.0 ^5   0/6    ^2    0 ^1     0
^zColt     : ^7 33.3 ^5   7/21   ^2    0 ^1     0 ^3        0
^zMP-40    :                 ^2    0 ^1     6 ^3        0
^zThompson : ^7 25.9 ^5  75/290  ^2   11 ^1     0 ^3        4
^zGrenade  : ^7 66.7 ^5   4/6    ^2    4 ^1     0
^zSyringe  : ^7100.0 ^5   8/8    ^2    0 ^1     0

^zDamage Given: ^72234    ^zTeam Damage : ^7147
^zDamage Recvd: ^71654    ^zBodies Gibbed: ^76 

/statsall result looks like this

[skipnotify]^7Overall stats for: ^zdonka ^7(^21^7 Round)

[skipnotify]Weapon     Acrcy Hits/Atts Kills Deaths Headshots
[skipnotify]-------------------------------------------------
[skipnotify]^zKnife    : ^7  0.0 ^5   0/6    ^2    0 ^1     0
[skipnotify]^zColt     : ^7 33.3 ^5   7/21   ^2    0 ^1     0 ^3        0
[skipnotify]^zMP-40    :                 ^2    0 ^1     6 ^3        0
[skipnotify]^zThompson : ^7 25.9 ^5  75/290  ^2   11 ^1     0 ^3        4
[skipnotify]^zGrenade  : ^7 66.7 ^5   4/6    ^2    4 ^1     0
[skipnotify]^zSyringe  : ^7100.0 ^5   8/8    ^2    0 ^1     0
[skipnotify]
^zDamage Given: ^72234    ^zTeam Damage : ^7147
[skipnotify]^zDamage Recvd: ^71654    ^zBodies Gibbed: ^76 

Please change the output method in /statsall to omit all [skipnotify] prefixes

**Comment by rtcw-nihi** [comment]
https://github.com/rtcw-nihi/ospx/commit/3f8420a2a070145b687d0b020509fa9539632e67
