### ISSUE TITLE
Ability to post JSON

### ISSUE THREAD

**Issue by donkz** [rtcw-nihi/ospx#156]
Implement an ability to POST a web request to an endpoint with the following headers:
matchid that is equal to ID of the match, type string
x-api-key for now rtcwproapikeythatisjustforbasicauthorization

Notes:
-data should be base64 encoded
-url , apikey should be stored in a default server variable with an option to override i suppose.
-trying to make https://rtcwproapi.donkanator.com working as URL

Good test for now (use linux or git bash to run this)

curl --location --request POST 'https://rtcwproapi.donkanator.com/matches' \
--header 'matchid: good-curl-test-name-1234-5678-9012' \
--header 'x-api-key: rtcwproapikeythatisjustforbasicauthorization' \
--data-raw 'ewogICAgImdsb3NzYXJ5IjogewogICAgICAgICJ0aXRsZSI6ICJleGFtcGxlIGdsb3NzYXJ5IiwKCQkiR2xvc3NEaXYiOiB7CiAgICAgICAgICAgICJ0aXRsZSI6ICJTIiwKCQkJIkdsb3NzTGlzdCI6IHsKICAgICAgICAgICAgICAgICJHbG9zc0VudHJ5IjogewogICAgICAgICAgICAgICAgICAgICJJRCI6ICJTR01MIiwKCQkJCQkiU29ydEFzIjogIlNHTUwiLAoJCQkJCSJHbG9zc1Rlcm0iOiAiU3RhbmRhcmQgR2VuZXJhbGl6ZWQgTWFya3VwIExhbmd1YWdlIiwKCQkJCQkiQWNyb255bSI6ICJTR01MIiwKCQkJCQkiQWJicmV2IjogIklTTyA4ODc5OjE5ODYiLAoJCQkJCSJHbG9zc0RlZiI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgInBhcmEiOiAiQSBtZXRhLW1hcmt1cCBsYW5ndWFnZSwgdXNlZCB0byBjcmVhdGUgbWFya3VwIGxhbmd1YWdlcyBzdWNoIGFzIERvY0Jvb2suIiwKCQkJCQkJIkdsb3NzU2VlQWxzbyI6IFsiR01MIiwgIlhNTCJdCiAgICAgICAgICAgICAgICAgICAgfSwKCQkJCQkiR2xvc3NTZWUiOiAibWFya3VwIgogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfQp9'

**Comment by rtcw-nihi** [comment]
Successfully completed within 'C' code using libcurl.
