### ISSUE TITLE
Fix and enhance JSON for round

### ISSUE THREAD

**Issue by donkz** [rtcw-nihi/ospx#157]
[ProJSON.xlsx](https://github.com/rtcw-nihi/ospx/files/5625643/ProJSON.xlsx)

This is a tracking issue for RTCWPro producing a JSON with match stats. See the xlsx attached for details.

Attached file (first tab only) contains:
Column C: Current available JSON format. It has a few errors that make it unparseable
Column A: same , but fixed JSON .  A few comas and brackets are added
Columns GHI: contain proposed additions, priority, and comments.

**Comment by donkz** [comment]
![unnamed](https://user-images.githubusercontent.com/10265890/101514879-5ebd7a00-3943-11eb-9415-b531f4a27719.png)
updated suggestions

**Comment by rtcw-nihi** [comment]
I would say this is pretty much done.  Just need to confirm the 'default output' format.
