### ISSUE TITLE
Lag spike at beginning of round

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#173]
Could be caused by cvar restrictions working as we changed the format on the 1.0.1 update and that is when the issue started occurring.  This is probably occuring on the following methods:

g_svrcmds -> G_UpdateSvCvars
cg_svrcmds -> CG_UpdateSvCvars

If no obvious issue stands out perhaps we can do this on ready up - when all players are ready, do this logic, then start the countdown that way the playing round is not affected

**Comment by krazykaze81** [comment]
Confirmed cvar limiting is causing lag spike

**Comment by rtcw-nihi** [comment]
ef00808e05ee44e5b4cee725e784f5faa2e7d9cc
