### ISSUE TITLE
Player with panzer can show 0.00 accuracy in end of round stats

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#184]
Wstats will show correct accuracy but isn't translating to end of round print out.  This may happen when accuracy is above 100% - panzer shots a lot of times kill more than 1 person resulting in very high accuracies

**Comment by rtcw-nihi** [comment]
https://github.com/rtcw-nihi/ospx/commit/c7badf5ebb3421fd0a89825e8eefca52fabd74fd
