### ISSUE TITLE
Freecam/change spectating player during pause

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#185]
When the game is paused, as a spec, you are locked to the player you were watching when the game is paused, unless you have people bound to keys, would be nice to sort of get off that locked view and rotate to different players and/or go into freecam - this works in OSP

**Comment by rtcw-nihi** [comment]
https://github.com/rtcw-nihi/ospx/commit/4e26e22a8ccd089af70f8d056a6f82ad598e72e6
