### ISSUE TITLE
Update the GeoIP database

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#186]
From a euro player: My flag started out as UK but then after some time (maybe a vid restart?) it went to the default question mark flag. I wasn’t on a VPN.

Other issues people have reported saying that their flag is not the correct country.

**Comment by rtcw-nihi** [comment]
updated: https://github.com/rtcw-nihi/ospx/commit/0efc985f002e1562d9704c7da933973f3a922365
