### ISSUE TITLE
Round time and respawn time keep running under pause

### ISSUE THREAD

**Issue by wolf6542** [rtcw-nihi/ospx#198]

**Comment by krazykaze81** [comment]
This is already fixed in master

**Comment by rtcw-nihi** [comment]
It is due to g_noteamswitching 1.  Pause works as it should with g_noteamswitching 0.

**Comment by rtcw-nihi** [comment]
https://github.com/rtcw-nihi/ospx/commit/3478dea6a2fe386770ee14a7f394c5dbc8c28100

**Comment by rtcw-nihi** [comment]
https://github.com/rtcw-nihi/ospx/commit/bf3b73a9ec33c1739163347b5251e07d640b584e
