### ISSUE TITLE
Check headshot hitbox for a crouching panzer

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#209]
Might need some adjustments

**Comment by wolf6542** [comment]
Not good currently, for nades as well.
![shot0004](https://user-images.githubusercontent.com/60988055/103694510-be8b5d00-4fa3-11eb-8c22-6d99539cf26f.jpg)
![shot0003](https://user-images.githubusercontent.com/60988055/103694514-bf23f380-4fa3-11eb-8497-1705751e856a.jpg)
![shot0002](https://user-images.githubusercontent.com/60988055/103694515-bfbc8a00-4fa3-11eb-90c7-4d0e77ad2fc2.jpg)
![shot0001](https://user-images.githubusercontent.com/60988055/103694517-bfbc8a00-4fa3-11eb-9cc1-6455acee4919.jpg)
![shot0008](https://user-images.githubusercontent.com/60988055/103694519-bfbc8a00-4fa3-11eb-8eb8-66836cbbed1b.jpg)
![shot0007](https://user-images.githubusercontent.com/60988055/103694521-c0552080-4fa3-11eb-8a1e-973770bc961a.jpg)
![shot0006](https://user-images.githubusercontent.com/60988055/103694522-c0552080-4fa3-11eb-92a5-da8b0c4f0f62.jpg)
![shot0005](https://user-images.githubusercontent.com/60988055/103694524-c0edb700-4fa3-11eb-9003-f2dd98130147.jpg)

**Comment by wolf6542** [comment]
Discard the above images. Testing was not done properly.
Closing this.
![shot0001](https://user-images.githubusercontent.com/60988055/104571251-8c40c600-565b-11eb-8fa6-b1c0bc9cf3f9.jpg)
![shot0002](https://user-images.githubusercontent.com/60988055/104571254-8cd95c80-565b-11eb-8fff-5f6f4c565091.jpg)
![shot0003](https://user-images.githubusercontent.com/60988055/104571256-8d71f300-565b-11eb-9996-2dcd0fe31339.jpg)
![shot0004](https://user-images.githubusercontent.com/60988055/104571258-8d71f300-565b-11eb-8bdc-21d541c31a8a.jpg)

**Comment by krazykaze81** [comment]
![panzer-stand](https://user-images.githubusercontent.com/45461774/104637790-41cb4380-5673-11eb-9872-8b84ebab1305.jpg)
![panzer-crouch](https://user-images.githubusercontent.com/45461774/104637802-455eca80-5673-11eb-9569-f1fd07e3205e.jpg)

For Mullins
