### ISSUE TITLE
When a player gets revived they are affected by knockback

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#214]
I think we need to replicate OSP here and make sure that when a revived player has temporary invulnerability they cannot be affected by knockback

crumbs 1/7/2021 at 10:23 AM
I was trying to gib and he got revived, but my stabs were moving him before he was allowed to move

**Comment by rtcw-nihi** [comment]
This shouldn't happen anymore: https://github.com/rtcw-nihi/ospx/pull/233/commits/a4786bef7f3749f8899444397bf44171de6b1e52
