### ISSUE TITLE
Opening scoreboard after ready countdown crashes game

### ISSUE THREAD

**Issue by eamonwoortman** [rtcw-nihi/ospx#22]
Pressing scoreboard during the countdown phase, soon as everyone's readied will crash the game

**Comment by rtcw-nihi** [comment]
I have not been able to replicate this crash.  Can anyone else?

**Comment by krazykaze81** [comment]
I recreated this yesterday on my local server.  I had g_mingameclients set to 1, readied up, countdown started, pressed scores button and client instantly crashed

**Comment by eamonwoortman** [comment]
Should be fixed now in the latest `osp-features` branch

**Comment by krazykaze81** [comment]
Fixed verified
