### ISSUE TITLE
+wstats gets stuck in some cases

### ISSUE THREAD

**Issue by eamonwoortman** [rtcw-nihi/ospx#24]
when in +wstats and pressing to next player, i still see the stats of the first player i specced
sometimes +wstats gets stuck permanently on
i use alt + z to minimize rtcw
when i maximize it, it still is there

**Comment by rtcw-nihi** [comment]
Issue is fixed. I did thorough testing but we probably need more before closing the issue.

**Comment by krazykaze81** [comment]
Changes look good to me - closing.
