### ISSUE TITLE
Hitsounds not working properly

### ISSUE THREAD

**Issue by eamonwoortman** [rtcw-nihi/ospx#26]
btw i can hear hitsounds, but other players can't - KK comment (I don't want hitsounds implemented)

-- Remove for now

**Comment by rtcw-nihi** [comment]
This is not a bug.  The server can turn off hitsounds to all clients by specifying 'g_hitsounds 0'.  If 'g_hitsounds 1' then the client can turn on/off hitsounds by using 'cg_hitsounds 1/0'
