### ISSUE TITLE
Menu in general feels pretty laggy

### ISSUE THREAD

**Issue by eamonwoortman** [rtcw-nihi/ospx#27]
menu in general feels pretty laggy, weaponstats gets often stuck and will ignore input if used repeatedly, same for scoreboard

**Comment by rtcw-nihi** [comment]
I was unable to replicate the scoreboard issue but +wstats and +stats menu have been fixed.  Some more testing wouldn't hurt as well as checking if the scoreboard really is an issue.

**Comment by krazykaze81** [comment]
I haven't seen any lag after the fix so I'm going to close this.
