### ISSUE TITLE
LT Info feature is bugged

### ISSUE THREAD

**Issue by eamonwoortman** [rtcw-nihi/ospx#32]
it'll randomly show "MP40 Grenades:: 0" on my center screen too, can't really tell whats causing it
Empty gun does not auto swap to pistols either, as in 0/0 gun, even with autoswitch on empty mag disabled on osp/etpro a 0/0 gun would always swap. - KK comment I added the LT Info from ospx for this so I guess it's buggy

Maybe disable it for now?

**Comment by krazykaze81** [comment]
I think the LTInfo method needs to be called from CG_DrawCrosshairNames and use CG_DrawStringExt to display the ammo for the person you are looking at

**Comment by krazykaze81** [comment]
Feature implemented
