### ISSUE TITLE
If i drop a weapon i cant pick it up anymore 

### ISSUE THREAD

**Issue by eamonwoortman** [rtcw-nihi/ospx#33]
If i drop a weapon i cant pick it up anymore - KK comment I haven't had issues with dropweapon so not sure why this happened

Confirmed with Plaz - dropweapon should be disabled for medic and engineer - only classes that can drop are LT and Soldier

**Comment by wolf6542** [comment]
See g_unlockWeapons.

**Comment by rtcw-nihi** [comment]
I removed the ability for medics to drop their weapons.  I will let everyone else decide if we want this controlled by a cvar rather than permanently disabled
