### ISSUE TITLE
During matches, in pause mode, allow players to join

### ISSUE THREAD

**Issue by eamonwoortman** [rtcw-nihi/ospx#36]
players can not rejoin teams during match - this is an issue in case there's dropouts due to crashes/999s/whatever

**Comment by rtcw-nihi** [comment]
This only occurs when 'g_noteamswitching = 1'.  Players can join during pause when this cvar is set to 0. Easiest/quickest Solution: Either remove 'g_noteamswitching' entirely or make sure it is set to 0 in the config?

**Comment by rtcw-nihi** [comment]
Changed default config 'g_noteamswitching 0' so that players can join during pause.  A better and permanent solution will follow though.

**Comment by krazykaze81** [comment]
Fixed this with latest PR - added g_noteamswitching 1 back into config and fixed logic so specs can join teams during pause
