### ISSUE TITLE
when taking ammo or med pack it doesnt show the notification on bottom right like '20 health' or so

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#38]
when taking ammo or med pack it doesnt show the notification on bottom right like '20 health' or so

this could be an issue in cg_draw - maybe they don't have cg_drawPickupItems set to 1?

			// OSPx - In warmup we print ready intel there..
			if (!cgs.gamestate == GS_WARMUP || cg_drawPickupItems.integer )
				CG_DrawPickupItem();

**Comment by rtcw-nihi** [comment]
Fixed.  Use 'cg_drawPickupItems 1' to get these notifications.  I set the default to 0 but that can be changed if anyone thinks it should be.
