### ISSUE TITLE
gib stats and accuracy inconsistent

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#39]
Gib stats are not working correctly under the following scenarios:

shooting/knifing enemy to gib
instant gib from nade/airstrike/artillery

Wstats and stats are reporting different accuracy - shots fire and shots hit target
8/20 on one window
8/14 on other window

**Comment by rtcw-nihi** [comment]
We should make these into two separate issues but I was not able to replicate "Wstats and stats are reporting different accuracy - shots fire and shots hit target".  More testing may be needed but from what I found is '\+stats', '\+wstats', and '\stats' all agree in hits/shots counts

**Comment by krazykaze81** [comment]
This looked correct the last time I look at it so I'm closing this for now.
