### ISSUE TITLE
Dead bodies grab spawn flags

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#43]
Happens in OSP - change spawnpoint flags so dead bodies cannot grab flags

**Comment by rtcw-nihi** [comment]
https://github.com/rtcw-nihi/ospx/commit/5c0be06bcc054c0f9c0801254b66bc7d61d9e35a
Seems to do the trick. I was unable to replicate the issue with this fix while without I could easily replicate it.
