### ISSUE TITLE
Player model too tall to walk in village cellar up the stairs

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#51]
Not sure of cause of this but it looks like the player model could be taller than vanilla and player cannot walk up the stair in village cellar without crouching.

**Comment by rtcw-nihi** [comment]
Identified the potential reason (the player bounding box) and committed a potential fix....haven't checked it though.

**Comment by krazykaze81** [comment]
Confirmed issue fixed
