### ISSUE TITLE
Server config print out with typos

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#53]
Reported by Virkes and Euros - when round starts the server prints out stuff form the ET config changes we added and has typos in it.  I haven't been able to find anything with these typos

sv_cvar cl_maxp**aa**ckets EQ 100
sv_cvar snaps **EQQ** 40
sv_cvar com_max**ff**ps 40 125

The defaulcomp config has these WITHOUT typos
command "sv_cvar rate EQ 25000"
command "sv_cvar cl_maxpackets EQ 100"
command "sv_cvar snaps EQ 40"
command "sv_cvar com_maxfps IN 40 125"

**Comment by krazykaze81** [comment]
I think this might be something in Nihi's server configs.  I am not seeing that show up locally.

**Comment by rtcw-nihi** [comment]
The config that the server is using does not have the typos.   I imagine it is a parsing error that most likely stems from the 'wolfded' the server is using. Time is not really on my side but I will try recompiling an updated wolfded to confirm.

**Comment by rtcw-nihi** [comment]
It was the wolfded.
