### ISSUE TITLE
End of round sound

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#54]
In OSP the end of round says one of the following
1) allies win then stock sound
2) axis win then the stock sound

Currently neither sounds are playing correctly.  I tried using CHAN_ANNOUNCER but it still doesn't work.

**Comment by krazykaze81** [comment]
Fix added - needs to be tested in live server

**Comment by wolf6542** [comment]
I'm being told both sounds used to work in the original repo, so we might need to look back.
Another option is to move one of them with APSound to checkExitRules and matchInfoDump respectively, but that's a lazy fix.
