### ISSUE TITLE
Reports @rtcwpro SA server

### ISSUE THREAD

**Issue by Fox3333** [rtcw-nihi/ospx#71]
Hey, im going to list some details we have been noticing in SA server using rtcwpro. Virkez pointing this out. 

*Speclock : for example: you do /speclock in round 1 as axis. Round 2 automatically unlock axis and  you can spec them.
*During warmup, you cant see who is ready and who isnt. Theres a question mark right next to the name
*During warmup, the clock keeps running. For example: allies set a time in round 1 of 2 minutes. During the warmup of round 2 you can hear the sound effect : 2 minutes lets go or the 30 seconds move move !
*Sometimes  you cant see what the vote is about. 
*Stats are bugged when uploading to krisofwin stats generator. http://krisofwin.com/stats/stats/2020.Sep.18.%2019h38m53s.html
*Stats(kills, deaths, etc) keeps accumulating map after map.

**Comment by krazykaze81** [comment]
*During warmup, the clock keeps running. For example: allies set a time in round 1 of 2 minutes. During the warmup of round 2 you can hear the sound effect : 2 minutes lets go or the 30 seconds move move - this issue was fixed after September 11 build
