### ISSUE TITLE
Issue placeholder

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#86]
Some bugs we noticed when playing last night. Replay here showing some of the bugs: https://www.twitch.tv/videos/760703714

- Player health always red in spectator mode (as @ZeD{ pointed out) (KK -> check out cg_drawselectedplayerhealth)
- Our PF had 0 accuracy one round despite getting kills (KK - might be an issue from porting FFE fix in g_weapon.c)
- Spec views dead player’s spec rather than switching to another living player
- When the game is paused, as a spec, you are locked to the player you were speccing when the game paused, unless you have people bound to keys, would be nice to sort of get off that locked view and rotate to different players and/or go into freecam
- My flag started out as UK but then after some time (maybe a vid restart?) it went to the default question mark flag. I wasn’t on a VPN.

**Comment by rtcw-nihi** [comment]
"Player health always red in spectator mode (as @zed{ pointed out) (KK -> check out cg_drawselectedplayerhealth)" has been fixed.

**Comment by krazykaze81** [comment]
Created individual issues from above issues.
