### ISSUE TITLE
Demo playback

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#89]
Issues with demo playback

"View Demos" doesn't show the demos - I added the ui_demoDir cvar and that works but it's not showing all the folder structure

Adlad reported that demo playback isn't working correctly  -> "My rtcwpro demos always seem to cause a game crash about a minute in, using Seismovision 3"

The demo controls Nate added in ospx are kind of working but not really - you can press Tab and it brings up the menu but not all the features are as nice as OSP.

**Comment by wolf6542** [comment]
Just to pin down the issues I've noticed with the OSP demo pop up window features:
The demo timer is amiss/not working;
the wallhack is amiss/not working;
status window is amiss/not working;

About the crash - tried to reproduce it with a demo that supposedly crashes, but all was fine on my end.
