### ISSUE TITLE
Pause issues

### ISSUE THREAD

**Issue by krazykaze81** [rtcw-nihi/ospx#92]
Murkey tested pause on the server and said the following:

i guess /pause still has problems
i threw a grenade
did /pause
waited 20-30 sec
unpaused
and the grenade stood there for like a minute then blew up
hit the floor
and sat there

same for airstrike sits on ground for a long while
also it uses your 'old' location
where you paused
the airstrike i mean

for example:
1) you throw airstrike
2) you pause
3) the airstrike registers where you are when you paused
4) the airstrike is not meant to register your location until it says 'affirmative on the way'
5) uses old location (atm)

**Comment by rtcw-nihi** [comment]
clients not being able to join on pause: https://github.com/rtcw-nihi/ospx/commit/faea60cf3e1ce415e98b27372fd7fb3219d6525a
grenade/as fix: https://github.com/rtcw-nihi/ospx/commit/3f74e768bea3f937498b7965db9274e4df30632c
